### ISSUE TITLE
umi collapse fails with fastq input

### ISSUE THREAD

**Issue by gfialk** [Daniel-Liu-c0deb0t/UMICollapse#1]
umicollapse is failing whan using fastq input. The command I'm running is:
umicollapse fastq -i in.fastq.gz -o out.fastq.gz
and I'm getting the following error:
Exception in thread "main" java.lang.ClassCastException: class umicollapse.util.FASTQRead cannot be cast to class umicollapse.util.SAMRead (umicollapse.util.FASTQRead and umicollapse.util.SAMRead are in unnamed module of loader 'app')
	at umicollapse.merge.MapQualMerge.merge(MapQualMerge.java:9)
	at umicollapse.main.DeduplicateFASTQ.deduplicateAndMerge(DeduplicateFASTQ.java:53)
	at umicollapse.main.Main.main(Main.java:166)

**Comment by Daniel-Liu-c0deb0t** [comment]
That's because FASTQ reads do not have a mapping quality, so the default mapping quality merging scheme cannot be used. Try adding `--merge avgqual` to the command-line arguments.

**Comment by Daniel-Liu-c0deb0t** [comment]
A better warning (or a different default setting) probably should be provided, so this is an open issue.

**Comment by gfialk** [comment]
Hi Daniel.

Thanks so much for your quick and helpfull response.
I was wandering if there was any way of getting the deduplication
statistics when I collapse a fastq file with UMICollapse? (something
similar to the --output-stats of umi-tools)

Best,
Gavriel

‫בתאריך יום ג׳, 24 במרץ 2020 ב-2:49 מאת ‪Daniel Liu‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Daniel-Liu-c0deb0t** [comment]
Currently, there is no way to do so. Of course, this should not be too hard to implement as a optional flag, like UMI-tools. However, I chose to not implement it because efficiency must be sacrificed in order to collect extra statistics.

**Comment by Daniel-Liu-c0deb0t** [comment]
When deduplicating FASTQ files, merging using average quality scores is now the default, so this issue is resolved.

**Comment by gfialk** [comment]
Great!
Thanks for the update
