### ISSUE TITLE
Unable to access jarfile umicollapse.jar when running from another directory

### ISSUE THREAD

**Issue by divibisan** [Daniel-Liu-c0deb0t/UMICollapse#24]
It's possible this is an issue with my setup, but whenever I try to run UMICollapse from any directory than the one it's installed in (I've added the UMICollapse directory to my PATH), I get the following error `Error: Unable to access jarfile umicollapse.jar`. I do not get this error if I cd into the UMICollapse directory and call it from there, or if I edit `umicollapse` to give the full, absolute path to umicollapse.jar in the `-jar` argument.

I'm using `openjdk version "11.0.19" 2023-04-18 LTS` on an EC2 instance running Amazon Linux. I've gotten the same issue when UMICollapse was installed on the same EBS as the data (in my home folder) and with it installed on a mounted EFS.

I can deal with this issue, but it makes it more difficult to incorporate into my pipeline. Thanks!

**Comment by Daniel-Liu-c0deb0t** [comment]
Yup the `umicollapse` script looks for the `jar` file locally. You should just edit the script and insert the absolute path to work around this issue.

**Comment by CharlotteAnne** [comment]
Hi - I've gone ahead and make a conda package for UMICollapse >> https://anaconda.org/bioconda/umicollapse
users can now install using the command conda install -c bioconda umicollapse. This will probably make your install much easier.
