### ISSUE TITLE
bioconda for nf-core module

### ISSUE THREAD

**Issue by CharlotteAnne** [Daniel-Liu-c0deb0t/UMICollapse#25]
Hi!

Love this software, me and colleagues have written an nf-core Nextflow module for your tool (https://github.com/nf-core/modules/pull/3368), but to get it accepted your tool needs to be in bioconda - any chance you'd have some spare time to do this? (there is a talk on how to do this by nf-core here https://nf-co.re/events/2022/bytesize-40-software-packaging)

Let me know what you think!

**Comment by Daniel-Liu-c0deb0t** [comment]
Hey, sorry for the delay. Is this still needed?
