### ISSUE TITLE
java.lang.NoClassDefFoundError: htsjdk/samtools/SamReaderFactory

### ISSUE THREAD

**Issue by umasstr** [Daniel-Liu-c0deb0t/UMICollapse#3]
EDIT

jarfile curl links are no longer valid. Sorry I missed this. May want to update htsjdk-2.19.0.jar and snappy-java-1.1.7.3.jar links. 

> Hi Daniel,
> 
> I am trying to de-duplicate sorted and indexed bams, but this error is produced with every sample. Thanks for the help. 
> 
> ```
> ~/UMICollapse$ for i in *.sort.bam; do ./umicollapse bam -i $i -o ${i%.sort*}.dup.bam;done
> 
> Arguments       [bam, -i, i504_i719_S1.sort.bam, -o, i504_i719_S1.dup.bam]
> Exception in thread "main" java.lang.NoClassDefFoundError: htsjdk/samtools/SamReaderFactory
>         at umicollapse.main.DeduplicateSAM.deduplicateAndMerge(DeduplicateSAM.java:36)
>         at umicollapse.main.Main.main(Main.java:169)
> Caused by: java.lang.ClassNotFoundException: htsjdk.samtools.SamReaderFactory
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
>         ... 2 more````

**Comment by Daniel-Liu-c0deb0t** [comment]
I've updated the curl URLs in the readme. Thanks for letting me know!
